### ISSUE TITLE
BOM is not stripped from the header of the UTF-8 file, if it exists.

### ISSUE THREAD

**Issue by pcgamez** [JLChnToZ/selfreloadjson#1]
Getting the error below and fixed with this patch on line 106 (index.js)

`if (rawFile.charCodeAt(0) == 65279) rawFile = rawFile.substr(1);`

> [2016-08-15 21:59:05] [LOG]   SyntaxError: Unexpected token ?
>     at Object.parse (native)
>     at updateFile (C:\xampp\htdocs\mvm\portal\node_modules\self-reload-json\index.js:110:38)
>     at resume (C:\xampp\htdocs\mvm\portal\node_modules\self-reload-json\index.js:62:7)
>     at new SelfReloadJSON (C:\xampp\htdocs\mvm\portal\node_modules\self-reload-json\index.js:128:5)
>     at Object.<anonymous> (C:\xampp\htdocs\mvm\portal\mvm_customer_portal.js:419:13)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> SyntaxError: Unexpected token ?
>     at Object.parse (native)
>     at updateFile (C:\xampp\htdocs\mvm\portal\node_modules\self-reload-json\index.js:110:38)
>     at resume (C:\xampp\htdocs\mvm\portal\node_modules\self-reload-json\index.js:62:7)
>     at new SelfReloadJSON (C:\xampp\htdocs\mvm\portal\node_modules\self-reload-json\index.js:128:5)
>     at Object.<anonymous> (C:\xampp\htdocs\mvm\portal\mvm_customer_portal.js:419:13)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)

**Comment by JLChnToZ** [comment]
Sorry about that late to replay your issue,. It is better to attach a pull request of your fix instead of leaving only the message, thanks.

**Comment by pcgamez** [comment]
Thanks for the recommendation, I'm a rookie here
