### ISSUE TITLE
Error while reloading

### ISSUE THREAD

**Issue by feeleep75** [JLChnToZ/selfreloadjson#2]
Hi - I am trying to reload json file like this:

```
{"data": 
    {
        "a": [8001],
        "b": [8002],
        "c": [8003],
        "d": [8004, 8005]
    }
}
```

and while reloading I get following messages:

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at updateFile (/root/node_modules/self-reload-json/index.js:106:38)
    at FSWatcher.onFileChange (/root/node_modules/self-reload-json/index.js:92:11)
    at FSWatcher.emit (events.js:98:17)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1051:12)
```

Will appreciate any advise...

**Comment by JLChnToZ** [comment]
While the JSON file is writing by any external program, it will trigger the update events several times in this package, even the writing process is not yet complete. It should be just fine after the writing process and the JSON should be successfully reloaded.
